### ISSUE TITLE
[FEATURE] Alternative Secret Generation Method in Documentation

### ISSUE THREAD

**Issue by websharkdev** [danybeltran/nextjs-typescript-and-mongodb#30]
Issue:
Title: Alternative Secret Generation Method in Documentation

Description:
In the documentation, there's a mention of generating a secret key using the command `openssl rand -base64 32`. However, not everyone may have access to the OpenSSL tool or may find it inconvenient to use. To address this, we can provide an alternative method for generating secrets. Instead of relying solely on command-line tools, we can suggest using a web-based service like https://generate-secret.vercel.app/32, where users can easily generate secrets of desired lengths. This would enhance accessibility and convenience for users who may not have access to command-line tools or prefer a more user-friendly approach to generating secrets.

**Comment by danybeltran** [comment]
Thanks @websharkdev! More information about alternative ways to generate `NEXTAUTH_SECRET` was added in #33 : ))
