### ISSUE TITLE
[FEATURE] Insufficient Documentation on MongoDB Connection

### ISSUE THREAD

**Issue by websharkdev** [danybeltran/nextjs-typescript-and-mongodb#31]
**Problem Description:**
The documentation lacks information on how to properly connect to the MongoDB database. It does not specify the database name, and there is no information on which URL to use for connection.

**Expected Behavior:**
The documentation should contain detailed information on how to configure the connection to MongoDB. This includes specifying the database name and providing an example URL for connecting to MongoDB.

**Proposed Solution:**
Add a section to the documentation dedicated to setting up the connection to MongoDB. This section should specify the database name used in the application and provide an example URL for connecting to MongoDB.

**Additional Information:**
The absence of this information makes it difficult for developers to properly configure the connection to the MongoDB database, which may lead to errors when working with the application.

**Tags:**
documentation, MongoDB, connection, database, information, development, code examples

**Priority:**
Medium

**Comment by websharkdev** [comment]
![image](https://github.com/danybeltran/nextjs-typescript-and-mongodb/assets/47607282/f1c1d8fb-732a-4437-b52e-c5e2befd0a1f)

UPD: I've been racking my brain for the second day on how to connect the database. Can u help me?

**Comment by danybeltran** [comment]
Thank for the suggestion @websharkdev! More information about Connecting to MongoDB was added to the docs in #33

**Comment by danybeltran** [comment]
Thanks for the suggestion @websharkdev! More information about Connecting to MongoDB was added to the docs in #33
